<?php
$currentPage = 'websites';
require_once 'includes/admin_header.php';
require_once '../includes/App.php';
App::boot();
$pdo = App::db();
$tenantService = App::tenantSite();
$csrf = function_exists('csrf_token') ? csrf_token() : ($_SESSION['csrf_token'] ?? '');
$statusFilter = trim((string)($_GET['status'] ?? ''));
$roleFilter = trim((string)($_GET['role'] ?? ''));
$search = trim((string)($_GET['search'] ?? ''));

$where = [];
$params = [];
if ($statusFilter !== '') { $where[] = 'ts.lifecycle_status = ?'; $params[] = $statusFilter; }
if ($roleFilter !== '') { $where[] = 'ts.tenant_type = ?'; $params[] = $roleFilter; }
if ($search !== '') { $where[] = '(ts.site_title LIKE ? OR ts.slug LIKE ? OR u.name LIKE ? OR u.phone LIKE ?)'; array_push($params, "%$search%", "%$search%", "%$search%", "%$search%"); }
$sql = "SELECT ts.*, u.name AS owner_name, u.phone AS owner_phone FROM tenant_sites ts LEFT JOIN users u ON ((ts.tenant_type = 'organization' AND u.id = (SELECT user_id FROM organizations WHERE id = ts.tenant_id LIMIT 1)) OR (ts.tenant_type <> 'organization' AND u.id = ts.tenant_id))";
if ($where) $sql .= ' WHERE ' . implode(' AND ', $where);
$sql .= ' ORDER BY ts.updated_at DESC';
$stmt = $pdo->prepare($sql); $stmt->execute($params); $sites = $stmt->fetchAll(PDO::FETCH_ASSOC);
$orders = $pdo->query("SELECT * FROM website_orders ORDER BY created_at DESC LIMIT 25")->fetchAll(PDO::FETCH_ASSOC);
$tenantOptions = [];
foreach (['doctor', 'pharmacist', 'seller'] as $role) {
    $q = $pdo->prepare("SELECT id, name, phone FROM users WHERE role = ? ORDER BY name"); $q->execute([$role]);
    foreach ($q->fetchAll(PDO::FETCH_ASSOC) as $row) $tenantOptions[] = ['type' => $role, 'id' => $row['id'], 'label' => $row['name'] . ' - ' . $role];
}
$q = $pdo->query("SELECT id, name, phone FROM organizations WHERE status <> 'suspended' ORDER BY name");
foreach ($q->fetchAll(PDO::FETCH_ASSOC) as $row) $tenantOptions[] = ['type' => 'organization', 'id' => $row['id'], 'label' => $row['name'] . ' - organization'];
?>
<div class="p-4 sm:p-6 max-w-7xl mx-auto space-y-6">
    <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div><h1 class="text-2xl font-black text-primary flex items-center gap-2"><span class="material-symbols-outlined text-3xl">language</span>مدیریت شبکه وب‌سایت‌ها</h1><p class="text-sm text-slate-500 mt-1">Provision, review, publish, and operate tenant websites from one cockpit.</p></div>
        <button type="button" onclick="document.getElementById('provisionModal').classList.remove('hidden')" class="min-h-12 px-5 rounded-xl bg-primary text-white font-bold flex items-center gap-2"><span class="material-symbols-outlined">add_business</span>ایجاد وب‌سایت مالک</button>
    </div>
    <form class="flex flex-wrap gap-2" method="get"><input name="search" value="<?= htmlspecialchars($search) ?>" placeholder="جستجوی نام، اسلاگ یا تلفن" class="min-h-12 flex-1 min-w-[220px] rounded-xl border border-slate-200 px-4"><select name="status" class="min-h-12 rounded-xl border border-slate-200 px-3"><option value="">همه وضعیت‌ها</option><?php foreach (['draft','provisioned','customizing','published','suspended','archived'] as $s): ?><option value="<?= $s ?>" <?= $statusFilter === $s ? 'selected' : '' ?>><?= $s ?></option><?php endforeach; ?></select><select name="role" class="min-h-12 rounded-xl border border-slate-200 px-3"><option value="">همه نقش‌ها</option><?php foreach (['doctor','organization','pharmacist','seller'] as $r): ?><option value="<?= $r ?>" <?= $roleFilter === $r ? 'selected' : '' ?>><?= $r ?></option><?php endforeach; ?></select><button class="min-h-12 px-5 rounded-xl bg-slate-900 text-white font-bold">فیلتر</button></form>
    <section class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><div class="bg-white rounded-2xl border p-4"><p class="text-xs text-slate-500">کل وب‌سایت‌ها</p><strong class="text-2xl text-primary"><?= count($sites) ?></strong></div><div class="bg-white rounded-2xl border p-4"><p class="text-xs text-slate-500">منتشرشده</p><strong class="text-2xl text-emerald-600"><?= count(array_filter($sites, fn($s) => ($s['lifecycle_status'] ?? '') === 'published')) ?></strong></div><div class="bg-white rounded-2xl border p-4"><p class="text-xs text-slate-500">درخواست‌های جدید</p><strong class="text-2xl text-orange-600"><?= count(array_filter($orders, fn($o) => ($o['status'] ?? '') === 'pending')) ?></strong></div><div class="bg-white rounded-2xl border p-4"><p class="text-xs text-slate-500">بازدید تجمیعی</p><strong class="text-2xl text-primary"><?= number_format(array_sum(array_map(fn($s) => (int)$s['views_count'], $sites))) ?></strong></div></section>
    <section class="bg-white rounded-2xl border overflow-hidden"><div class="p-4 border-b"><h2 class="font-black text-lg">وب‌سایت‌های فعال و پیش‌نویس</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-right">سایت</th><th class="p-3 text-right">مالک</th><th class="p-3 text-right">نقش / تیِر</th><th class="p-3 text-right">وضعیت</th><th class="p-3 text-right">عملیات</th></tr></thead><tbody><?php foreach ($sites as $site): ?><tr class="border-t"><td class="p-3"><strong><?= htmlspecialchars($site['site_title']) ?></strong><div class="text-xs text-slate-500 font-mono" dir="ltr"><?= htmlspecialchars($site['slug']) ?>.asena.company</div></td><td class="p-3"><?= htmlspecialchars($site['owner_name'] ?: '—') ?><div class="text-xs text-slate-500"><?= htmlspecialchars($site['owner_phone'] ?: '') ?></div></td><td class="p-3"><?= htmlspecialchars($site['tenant_type']) ?><div class="text-xs text-slate-500"><?= htmlspecialchars($site['site_tier'] ?? 'enterprise') ?></div></td><td class="p-3"><span class="px-2 py-1 rounded-full text-xs font-bold bg-slate-100"><?= htmlspecialchars($site['lifecycle_status'] ?? 'published') ?></span></td><td class="p-3"><div class="flex flex-wrap gap-2"><a class="min-h-10 px-3 rounded-lg bg-slate-100 inline-flex items-center" target="_blank" href="../site.php?slug=<?= urlencode($site['slug']) ?>">پیش‌نمایش</a><a class="min-h-10 px-3 rounded-lg bg-primary text-white inline-flex items-center" href="../<?= htmlspecialchars($site['tenant_type']) ?>/site_builder.php">ویرایش</a><form method="post" action="../actions/admin_websites_action.php" onsubmit="return submitAdminWebsite(this)"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="action" value="update_site"><input type="hidden" name="site_id" value="<?= (int)$site['id'] ?>"><input type="hidden" name="lifecycle_status" value="<?= ($site['lifecycle_status'] ?? '') === 'published' ? 'suspended' : 'published' ?>"><input type="hidden" name="site_tier" value="<?= htmlspecialchars($site['site_tier'] ?? 'standard') ?>"><button class="min-h-10 px-3 rounded-lg bg-orange-100 text-orange-800"><?= ($site['lifecycle_status'] ?? '') === 'published' ? 'تعلیق' : 'انتشار' ?></button></form></div></td></tr><?php endforeach; if (!$sites): ?><tr><td colspan="5" class="p-8 text-center text-slate-500">هنوز وب‌سایتی ثبت نشده است.</td></tr><?php endif; ?></tbody></table></div></section>
    <section class="bg-white rounded-2xl border overflow-hidden"><div class="p-4 border-b"><h2 class="font-black text-lg">درخواست‌های راه‌اندازی</h2></div><div class="divide-y"><?php foreach ($orders as $order): ?><div class="p-4 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3"><div><strong><?= htmlspecialchars($order['full_name']) ?></strong><span class="text-xs text-slate-500 mr-2"><?= htmlspecialchars($order['archetype']) ?> / <?= htmlspecialchars($order['tier']) ?></span><div class="text-xs text-slate-500" dir="ltr"><?= htmlspecialchars($order['phone']) ?> · <?= htmlspecialchars($order['desired_slug']) ?>.asena.company</div></div><form method="post" action="../actions/admin_websites_action.php" onsubmit="return submitAdminWebsite(this)" class="flex gap-2"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="action" value="update_order"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><select name="status" class="min-h-10 rounded-lg border px-2"><?php foreach (['pending','needs_information','approved','provisioned','in_progress','published','rejected','cancelled'] as $s): ?><option value="<?= $s ?>" <?= $order['status'] === $s ? 'selected' : '' ?>><?= $s ?></option><?php endforeach; ?></select><button class="min-h-10 px-3 rounded-lg bg-slate-900 text-white">ذخیره</button></form></div><?php endforeach; if (!$orders): ?><div class="p-8 text-center text-slate-500">درخواستی وجود ندارد.</div><?php endif; ?></div></section>
</div>
<div id="provisionModal" class="hidden fixed inset-0 z-50 bg-black/60 p-4 flex items-center justify-center"><form method="post" action="../actions/admin_websites_action.php" onsubmit="return submitAdminWebsite(this)" class="bg-white rounded-2xl p-5 w-full max-w-xl space-y-3"><div class="flex justify-between items-center"><h2 class="font-black text-lg">ایجاد وب‌سایت برای مالک</h2><button type="button" onclick="document.getElementById('provisionModal').classList.add('hidden')" class="w-10 h-10 rounded-lg bg-slate-100">×</button></div><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="action" value="provision"><select name="tenant_key" onchange="const p=this.value.split(':');this.form.tenant_type.value=p[0];this.form.tenant_id.value=p[1]" class="w-full min-h-12 rounded-xl border px-3" required><option value="">انتخاب مالک موجود</option><?php foreach ($tenantOptions as $option): ?><option value="<?= $option['type'] ?>:<?= (int)$option['id'] ?>"><?= htmlspecialchars($option['label']) ?></option><?php endforeach; ?></select><input type="hidden" name="tenant_type"><input type="hidden" name="tenant_id"><div class="grid grid-cols-2 gap-3"><select name="archetype" class="min-h-12 rounded-xl border px-3"><?php foreach (['doctor','organization','pharmacist','seller'] as $v): ?><option value="<?= $v ?>"><?= $v ?></option><?php endforeach; ?></select><select name="site_tier" class="min-h-12 rounded-xl border px-3"><?php foreach (['basic','standard','premium','pharmacy','enterprise'] as $v): ?><option value="<?= $v ?>" <?= $v === 'standard' ? 'selected' : '' ?>><?= $v ?></option><?php endforeach; ?></select></div><input name="site_title" placeholder="عنوان وب‌سایت" class="w-full min-h-12 rounded-xl border px-3" required><input name="site_tagline" placeholder="شعار یا توضیح کوتاه" class="w-full min-h-12 rounded-xl border px-3"><input name="slug" placeholder="slug (اختیاری)" dir="ltr" class="w-full min-h-12 rounded-xl border px-3"><select name="lifecycle_status" class="w-full min-h-12 rounded-xl border px-3"><option value="draft">پیش‌نویس</option><option value="published">انتشار فوری</option></select><button class="w-full min-h-12 rounded-xl bg-primary text-white font-bold">ایجاد و ثبت بدون پرداخت</button></form></div>
<script>async function submitAdminWebsite(form){event.preventDefault();const r=await fetch(form.action,{method:'POST',body:new FormData(form)});const d=await r.json();if(d.success){location.reload();}else{alert(d.message||'خطا');}return false;}</script>
<?php require_once 'includes/admin_footer.php'; ?>
